# Heavily borrowed from https://github.com/symfony/dotenv/blob/master/Tests/DotenvTest.php
# Credit to Fabien Potencier <fabien@symfony.com>

on:
  - pull_request
  - push

name: CI

jobs:
  tests:
    name: Tests

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - "8.0"
          - "8.1"

        dependencies:
          - lowest
          - highest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Install PHP with extensions"
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: pcov
          extensions: dom, json, libxml, mbstring, pdo_sqlite, soap, xml, xmlwriter
          ini-values: assert.exception=1, zend.assertions=1

      - name: "Cache dependencies installed with composer"
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache
          key: php${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            php${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-

      - name: Install lowest dependencies with composer
        if: matrix.dependencies == 'lowest'
        run: composer update --no-ansi --no-interaction --no-progress --no-suggest --prefer-lowest

      - name: Install highest dependencies with composer
        if: matrix.dependencies == 'highest'
        run: composer update --no-ansi --no-interaction --no-progress --no-suggest

      - name: Run tests
        run: ./vendor/bin/phpunit
